controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.say(answerlist[randint(0, answerlist.length - 1)])
})
let answerlist: string[] = []
let mySprite: Sprite = null
game.setDialogFrame(img`
    ..ccaccaaccaaccaaccccc..
    .bddbaddbaddbaddbaccddb.
    addddcaddcaddbaddcadddda
    addddccaaccaabbaaccdddda
    acddbffffffffffffffbddba
    ccacffffffffffffffffccac
    caccffffffffffffffffcadc
    abdaffffffffffffffffadda
    addaffffffffffffffffadba
    cdacffffffffffffffffccac
    caccffffffffffffffffcadc
    abdaffffffffffffffffadda
    addaffffffffffffffffadba
    cdabffffffffffffffffccab
    cabbffffffffffffffffcadb
    abdaffffffffffffffffadda
    addaffffffffffffffffadba
    cdacffffffffffffffffccac
    caccffffffffffffffffcacc
    abddbffffffffffffffbddca
    addddccaabbaabbaaccdddda
    addddacddabddabddacdddda
    .addccabddabddabddabdda.
    ..aaaccaaccaaccaaccaaa..
    `)
game.setDialogTextColor(1)
game.showLongText("Welcome to Magic 8 Ball! Ask a question, press A to get an answer.", DialogLayout.Center)
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffffbbbbbbbbbfffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffffbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbfffffffffffffbbbbfffffffffffbbbfffffffffffffbbbbbbbbbbbbbbbbfffffbbbfffffffffffffffffbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbbffffffffffffbbbbffffffffffbbbbffffffffffffbbbbbfffffffbbbbbbffffbbbffffffffffffffffbbbbbbfffffbbbbbbbffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbbfffffffffffbbbbbffffffffffbbbbfffffffffffbbbbbfffffffffbbbbbffffbbbffffffffffffffffbbbbfffffffffbbbbbbfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbbbffffffffffbbbbbffffffffffbbbbbffffffffffbbbbffffffffffffbbbffffbbbfffffffffffffffbbbbffffffffffffbbbbfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbbbbffffffffbbbbbbffffffffffbbbbbfffffffffbbbbffffffffffffffffffffbbbffffffffffffffbbbbbfffffffffffffbbbfffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbbbbbffffffbbbbbbbfffffffffbbbbbbbffffffffbbbbffffffffffffffffffffbbbffffffffffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffbbbbbbbfffffbbbbbbbbfffffffffbbbbbbbbfffffffbbbfffffffffffffffffffffbbbbfffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbbbbbfffbbbbbfbbbbfffffffbbbbfbbbbffffffbbbbfffffffffffffffffffffbbbbffffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbbbbbffbbbbbffbbbbfffffffbbbbffbbbbfffffbbbbffffffffffffffffffffffbbbffffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfbbbbbbbbbffffbbbfffffffbbbfffbbbbfffffbbbfffffffffffffffffffffffbbbffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfbbbbbbbbfffffbbbfffffffbbbffffbbbffffbbbbfffffffffffffffffffffffbbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffbbbbbbffffffbbbfffffffbbbffffbbbffffbbbbfffffffffffffffffffffffbbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffbbbbfffffffbbbfffffffbbbffffbbbbfffbbbfffffffffffffffffffffffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffbbbfffffffbbbfffffffbbbffffbbbbfffbbbfffffffffffffffffffffffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbfffffffbbbfffffbbbfffbbbfffffffffffffffffffffffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbffffffbbbbfffffbbbbffbbbffffffffffffbbbbbffffffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbffffffbbbbfffffbbbbffbbbffffffffffbbbbbbbbbbbffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbffffffbbbbbbbbbbbbbbfbbbffffffffffbbbbbbbbbbbffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbffffffbbbbbbbbbbbbbbfbbbbfffffffffbbbbbbbbbbbffffbbbfffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbbfffffbbbbbbbbbbbbbbbbbbbfffffffffffffbbbffffffffbbbfffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbffffffffffffffbbbbffffbbbbffffffffbbbbfbbbbffffffffffffbbbffffffffbbbfffffffffffbbbbbffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffbbbffffbbbbfffffffffbbbfbbbbffffffffffffbbbffffffffbbbffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffbbbfffbbbbffffffffffbbbbfbbbbfffffffffffbbbffffffffbbbfffffffffffffbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffbbbfffbbbbffffffffffbbbbfbbbbbfffffffffbbbbffffffffbbbffffffffffffffbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffbbbfffbbbffffffffffffbbbffbbbbbffffffffbbbbffffffffbbbfffffffffffffffbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffbbbfffbbbffffffffffffbbbfffbbbbbbbffffbbbbfffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffbbbfffbbbffffffffffffbbbffffbbbbbbbbbbbbbbfffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffffffffbbbffffffffffffffffffffbbbbbbbbbbbbfffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffffffffbbbfffffffffffffffffffffffbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffbbbfffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfffbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbffffffffffffffbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbffffffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbfffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbfffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbfbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfffffffffbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbffffffffffffbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbfffffffffffffffffffbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffffffffffffffffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffffffffffffffffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffffffffffffffffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbfffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfffffffffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbffffffffffffbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
mySprite = sprites.create(img`
    . . . . . . . . . c c 8 . . . . 
    . . . . . . 8 c c c f 8 c c . . 
    . . . c c 8 8 f c a f f f c c . 
    . . c c c f f f c a a f f c c c 
    8 c c c f f f f c c a a c 8 c c 
    c c c b f f f 8 a c c a a a c c 
    c a a b b 8 a b c c c c c c c c 
    a f c a a b b a c c c c c f f c 
    a 8 f c a a c c a c a c f f f c 
    c a 8 a a c c c c a a f f f 8 a 
    . a c a a c f f a a b 8 f f c a 
    . . c c b a f f f a b b c c 6 c 
    . . . c b b a f f 6 6 a b 6 c . 
    . . . c c b b b 6 6 a c c c c . 
    . . . . c c a b b c c c . . . . 
    . . . . . c c c c c c . . . . . 
    `, SpriteKind.Player)
answerlist = [
"As I see it, yes",
"Better not tell you now",
"Concentrate and ask again",
"Don't count on it",
"Most likely",
"reply is hazy, try again",
"Without a doubt",
"YES",
"NO"
]
